#!/bin/bash
git clone https://github.com/mozilla-services/heka
cd heka
git apply /tmp/src/crewton-heka-kinesis.patch
cp /tmp/src/plugin_loader.cmake cmake/
source build.sh
make install
cpack
CPACK_DEBIAN_PACKAGE_VERSION=+kinesis make deb
mkdir -p /out
cp build/*.deb /out
